export { default as expoSVG } from '@/assets/svgs/expo.svg'
export { default as geminiSVG } from '@/assets/svgs/gemini.svg'
export { default as jwtSVG } from '@/assets/svgs/jwt.svg'
export { default as mercadopagoPNG } from '@/assets/svgs/mercadopago.png'
export { default as nextAuthSVG } from '@/assets/svgs/next-auth.svg'
export { default as reactNativeSVG } from '@/assets/svgs/reactnative.svg'
export { default as shadcnSVG } from '@/assets/svgs/shadcn.svg'
export { default as tanstackquerySVG } from '@/assets/svgs/tanstackquery.svg'
